from miscutil import conj as conj, disj as disj, ijoin as ijoin
from miscutil.subprocess import CommandResult as CommandResult, run_command as run_command
from typing import Any, List, Optional

class DockerCompose:
    on_directory: Any = ...
    def __init__(self, on_directory: Optional[str]=...) -> None: ...
    def run_command(self, *args: str, print_progress: bool=...) -> CommandResult: ...
    def up_in_background(self, cmd_args: List[str], mandatory_words: List[str], max_count: int=..., check_interval_in_sec: float=..., print_progress: bool=...) -> CommandResult: ...
    def down(self, print_progress: bool=...) -> CommandResult: ...
