from miscutil import DupableIterable as DupableIterable
from typing import Any, Callable, Iterable

NAN: Any

def nnan(nums: Iterable[float]) -> Iterable[float]: ...
def nan_if_error(func: Callable[[Any], float], data: Any) -> float: ...
def safe_max(*args: Any, **kwargs: Any) -> float: ...
