import unittest
from miscutil import yamljson as yamljson
from typing import Any

class TCWithGoldenFile(unittest.TestCase):
    maxDiff: Any = ...
    top_dir: Any = ...
    suffix_of_golden: Any = ...
    out_extension: Any = ...
    def __init__(self, top_dir: str, suffix_of_golden: str, *, out_extension: str=..., method_name: str=...) -> None: ...
